import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardHeader,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { useAccount, useWriteContract } from "wagmi";
import { ToastContainer, toast } from "react-toastify";
import { isAddress } from "viem";
import "react-toastify/dist/ReactToastify.css";
import { isURL } from "@/lib/utils";

const Home: NextPage = () => {
  const { writeContract } = useWriteContract();
  const { isConnected } = useAccount();

  const [formData, setFormData] = useState({
    userAddress: "",
    tokenURI: "",
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    let error = false;

    if (!isAddress(formData.userAddress)) {
      toast.error("Invalid user address");
      error = true;
    }

    if (!isURL(formData.tokenURI)) {
      toast.error("Invalid token URI");
      error = true;
    }

    if (error) return;

    console.log("Form submitted with data:", formData);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ToastContainer />

        <div className="flex flex-col gap-2 items-center justify-center mb-10">
          <h1 className={styles.title}>NFT Minter</h1>
          <ConnectButton />
        </div>

        <Card className="w-full max-w-md mx-auto">
          <CardHeader>
            <CardDescription>
              Fill in the form below to mint your NFT
            </CardDescription>
          </CardHeader>
          <form onSubmit={handleSubmit}>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="userAddress">User address</Label>
                <Input
                  type="text"
                  id="userAddress"
                  name="userAddress"
                  value={formData.userAddress}
                  onChange={handleChange}
                  placeholder="Enter the user address"
                  required
                  disabled={!isConnected}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="tokenURI">Token URI</Label>
                <Input
                  type="text"
                  id="tokenURI"
                  name="tokenURI"
                  value={formData.tokenURI}
                  onChange={handleChange}
                  placeholder="Enter the token URI"
                  required
                  disabled={!isConnected}
                />
              </div>
            </CardContent>
            <CardFooter>
              <Button disabled={!isConnected} type="submit" className="w-full">
                Mint
              </Button>
            </CardFooter>
          </form>
        </Card>
      </main>
    </div>
  );
};

export default Home;
